package tn.esprit.spring.entities;

public enum Zone  {
	 TATAOUINE,MEDNINE,GABES,KEBILI,TOZEUR,GAFSA,SIDI_BOUZID,SFAX,KASSERINE,KAIROUAN,MAHDIA,MOUNASTIR,SOUSSE,SILIANA,EL_KEF,ZAGHOUAN,BEJA,JANDOUBA,BIZERTE,NABEUL,TUNIS
	
}
